import type { Metadata } from 'next';
import { Outfit, Quicksand } from 'next/font/google';
import './globals.css';
import { StorageProvider } from '@/context/useStorage';

const outfit = Outfit({
	variable: '--font-outfit',
	subsets: ['latin'],
});

const quickSand = Quicksand({
	variable: '--font-quick-sand',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Financial Manager',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${outfit.variable} ${quickSand.variable} antialiased`}>
				<StorageProvider>{children}</StorageProvider>
			</body>
		</html>
	);
}
